package com.huobi.client.model;

import java.math.BigDecimal;

/**
 * The summary of trading in the market for the last 24 hours
 */
public class TradeStatistics {

  private long timestamp;
  private BigDecimal open;
  private BigDecimal close;
  private BigDecimal amount;
  private BigDecimal high;
  private BigDecimal low;
  private long count;
  private BigDecimal volume;

  /**
   * Get the UNIX formatted timestamp generated by server in UTC.
   *
   * @return The timestamp
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Get the opening price of last 24 hours.
   *
   * @return The open price.
   */
  public BigDecimal getOpen() {
    return open;
  }

  /**
   * Get the last price of last 24 hours.
   *
   * @return The last price.
   */
  public BigDecimal getClose() {
    return close;
  }

  /**
   * Get the aggregated trading volume in USDT.
   *
   * @return The aggregated trading volume.
   */
  public BigDecimal getAmount() {
    return amount;
  }

  /**
   * Get the high price of last 24 hours.
   *
   * @return The high price.
   */
  public BigDecimal getHigh() {
    return high;
  }

  /**
   * Get the low price of last 24 hours.
   *
   * @return The low price.
   */
  public BigDecimal getLow() {
    return low;
  }

  /**
   * Get the number of completed trades.
   *
   * @return The number of completed trades.
   */
  public long getCount() {
    return count;
  }

  /**
   * Get the trading volume in base currency of last 24 hours.
   *
   * @return The trading volume in base currency of last 24 hours.
   */
  public BigDecimal getVolume() {
    return volume;
  }

  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
  }

  public void setOpen(BigDecimal open) {
    this.open = open;
  }

  public void setClose(BigDecimal close) {
    this.close = close;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public void setHigh(BigDecimal high) {
    this.high = high;
  }

  public void setLow(BigDecimal low) {
    this.low = low;
  }

  public void setCount(long count) {
    this.count = count;
  }

  public void setVolume(BigDecimal volume) {
    this.volume = volume;
  }
}
