package com.huobi.client.model.event;

import com.huobi.client.model.PriceDepth;

/**
 * The price depth received by subscription of price depth.
 */
public class PriceDepthEvent {

  private String symbol;
  private Long timestamp;
  private PriceDepth data;

  /**
   * Get the symbol you subscribed.
   *
   * @return The symbol, like "btcusdt".
   */
  public String getSymbol() {
    return symbol;
  }

  /**
   * Get the UNIX formatted timestamp generated by server in UTC.
   *
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Get the price depth.
   *
   * @return The price depth data, see {@link PriceDepth}
   */
  public PriceDepth getData() {
    return data;
  }

  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public void setData(PriceDepth data) {
    this.data = data;
  }
}
