package com.huobi.client.model.event;

import com.huobi.client.model.Trade;
import java.util.List;

/**
 * The trade received by subscription of trade.
 */
public class TradeEvent {

  private String symbol;
  private Long timestamp;
  private List<Trade> tradeList;

  /**
   * Get the symbol you subscribed.
   *
   * @return The symbol, like "btcusdt".
   */
  public String getSymbol() {
    return symbol;
  }

  /**
   * Get the UNIX formatted timestamp generated by server in UTC.
   *
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Get the trade.
   *
   * @return The trade data, see {@link Trade}
   */
  public List<Trade> getTradeList() {
    return tradeList;
  }

  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public void setTradeList(List<Trade> tradeList) {
    this.tradeList = tradeList;
  }
}
